name: Build UltimateShop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package --batch-mode --no-transfer-progress

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: UltimateShop-jar
          path: target/UltimateShop-*.jar
